# -*- coding: utf-8 -*-
"""Davaleba_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Rg3PPkCpUqj77gx35lhy7KY3R4dfd2H
"""

!pip install fastapi uvicorn mlflow pydantic nest_asyncio pyngrok pandas numpy scikit-learn

import mlflow
import mlflow.sklearn
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

np.random.seed(42)
n_samples = 1000
study_hours = np.random.uniform(5, 30, n_samples)
attendance = np.random.uniform(60, 100, n_samples)
assignments = np.random.randint(5, 11, n_samples)
midterm_score = np.random.uniform(40, 100, n_samples)

final_score = (
    0.5 * study_hours
    + 0.3 * attendance
    + 2.0 * assignments
    + 0.4 * midterm_score
    + np.random.normal(0, 3, n_samples)
)
final_score = np.clip(final_score, 0, 100)

df = pd.DataFrame(
    {
        "study_hours": study_hours,
        "attendance": attendance,
        "assignments": assignments,
        "midterm_score": midterm_score,
        "final_score": final_score,
    }
)
df.to_csv("student_data.csv", index=False)

X = df[["study_hours", "attendance", "assignments", "midterm_score"]]
y = df["final_score"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

mlflow.set_experiment("Student_Performance_Analysis")

with mlflow.start_run() as run:
    model = LinearRegression()
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)
    mae = mean_absolute_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)

    mlflow.log_param("model_type", "LinearRegression")
    mlflow.log_param("train_size", 0.8)
    mlflow.log_metric("MAE", mae)
    mlflow.log_metric("R2_Score", r2)

    mlflow.sklearn.log_model(model, "student_score_model")

    active_run_id = run.info.run_id

print("-" * 50)
print(f"მოდელი წარმატებით გაიწვრთნა და დალოგდა MLflow-ში!")
print(f"Run ID: {active_run_id}")
print(f"MAE (საშუალო აბსოლუტური ცდომილება): {mae:.2f}")
print(f"R2 Score (სიზუსტე): {r2:.2f}")
print("-" * 50)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import mlflow.sklearn
# import numpy as np
# import pandas as pd
# from fastapi import FastAPI
# from pydantic import BaseModel, Field
# 
# app = FastAPI(
#     title="Student Performance Predictor API",
#     description="API სტუდენტის საბოლოო ქულის პროგნოზირებისთვის",
#     version="1.0"
# )
# 
# try:
#     experiment = mlflow.get_experiment_by_name("Student_Performance_Analysis")
#     runs = mlflow.search_runs(experiment_ids=[experiment.experiment_id])
#     last_run_id = runs.iloc[0].run_id
#     model_uri = f"runs://{last_run_id}/student_score_model"
#     model = mlflow.sklearn.load_model(model_uri)
#     print(f"წარმატებით ჩაიტვირთა მოდელი Run ID-დან: {last_run_id}")
# except Exception as e:
#     print("მოდელის ჩატვირთვისას დაფიქსირდა შეცდომა:", e)
# 
# class StudentData(BaseModel):
#     study_hours: float = Field(..., description="კვირაში სწავლის საათები", ge=0, le=168)
#     attendance: float = Field(..., description="დასწრების პროცენტი", ge=0, le=100)
#     assignments: int = Field(..., description="შესრულებული დავალებები", ge=0)
#     midterm_score: float = Field(..., description="შუალედური ქულა", ge=0, le=100)
# 
# @app.post("/predict", summary="საბოლოო ქულის პროგნოზირება")
# def predict_score(data: StudentData):
#     input_data = pd.DataFrame([{
#         'study_hours': data.study_hours,
#         'attendance': data.attendance,
#         'assignments': data.assignments,
#         'midterm_score': data.midterm_score
#     }])
# 
#     prediction = model.predict(input_data)[0]
#     final_pred = float(np.clip(prediction, 0, 100))
# 
#     return {
#         "status": "success",
#         "predicted_final_score": round(final_pred, 2),
#         "input_features": data.dict()
#     }
# 
# @app.get("/")
# def root():
#     return {"message": "Welcome to Student API. Append /docs to URL for Swagger UI."}

import asyncio
import nest_asyncio
import uvicorn

nest_asyncio.apply()


def run_server():
    uvicorn.run("app:app", host="0.0.0.0", port=8000, log_level="info")


import threading

server_thread = threading.Thread(target=run_server)
server_thread.start()
print("FastAPI სერვერი გაეშვა ფონურ რეჟიმში პორტზე 8000!")

import time
import requests

time.sleep(2)

test_student = {
    "study_hours": 18.5,
    "attendance": 95.0,
    "assignments": 9,
    "midterm_score": 82.0,
}

url = "http://127.0.0.1:8000/predict"

try:
    response = requests.post(url, json=test_student)
    print("სერვერის პასუხი (Response JSON):")
    print(response.json())
except Exception as e:
    print("კავშირის შეცდომა:", e)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train.py
# import mlflow
# import mlflow.sklearn
# import numpy as np
# import pandas as pd
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import mean_absolute_error, r2_score
# from sklearn.model_selection import train_test_split
# 
# # მონაცემების წაკითხვა
# df = pd.read_csv("student_data.csv")
# 
# X = df[['study_hours', 'attendance', 'assignments', 'midterm_score']]
# y = df['final_score']
# 
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# 
# mlflow.set_experiment("Student_Performance_Analysis")
# 
# with mlflow.start_run():
#     model = LinearRegression()
#     model.fit(X_train, y_train)
# 
#     predictions = model.predict(X_test)
#     mae = mean_absolute_error(y_test, predictions)
#     r2 = r2_score(y_test, predictions)
# 
#     # ლოგირება
#     mlflow.log_param("model_type", "LinearRegression")
#     mlflow.log_param("train_size", 0.8)
#     mlflow.log_metric("MAE", mae)
#     mlflow.log_metric("R2_Score", r2)
#     mlflow.sklearn.log_model(model, "student_score_model")
# 
# print("train.py ფაილი წარმატებით შეიქმნა!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# fastapi==0.110.0
# uvicorn==0.28.0
# mlflow==2.11.1
# scikit-learn==1.4.1.post1
# pandas==2.2.1
# numpy==1.26.4
# pydantic==2.6.4
# requests==2.31.0